# Generated by Django 5.1.5 on 2025-02-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicalrecord',
            table='medical_records',
        ),
    ]
