# Generated by Django 5.1.5 on 2025-02-08 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklist_types', '0001_initial'),
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('due_date', models.DateField()),
                ('task_status', models.IntegerField()),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.checklist')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist_types.checklisttype')),
            ],
        ),
    ]
