# Generated by Django 5.1.5 on 2025-02-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
