# Generated by Django 5.1.5 on 2025-03-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=250)),
                ('record_id', models.IntegerField()),
                ('url', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
    ]
