# Generated by Django 5.1.5 on 2025-03-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(max_length=250),
        ),
    ]
