# Generated by Django 5.1.5 on 2025-03-01 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachment',
            table='attachments',
        ),
    ]
