# Generated by Django 5.1.5 on 2025-03-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_alter_attachment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.TextField(),
        ),
    ]
